/**
 * Production SEO keyword packs — high-intent phrases for ranking free assessments.
 * Site-wide pack (~100) + per-topic packs for TestPage meta keywords.
 */

export const SITE_SEO_KEYWORDS = [
  'MindoraInsight',
  'free personality test',
  'free ADHD test',
  'free adult ADHD test',
  'free autism spectrum test',
  'free Big 5 test',
  'free Big Five personality test',
  'free 16 personalities test',
  'free MBTI style test',
  'free Enneagram test',
  'free depression screening test',
  'free love languages test',
  'free attachment style quiz',
  'free strengths finder test',
  'free career aptitude test',
  'free DISC assessment',
  'free emotional intelligence test',
  'free EQ test',
  'free archetype test',
  'free political compass test',
  'free character strengths test',
  'free BPD traits quiz',
  'free bipolar spectrum screen',
  'free narcissism test',
  'free trauma patterns quiz',
  '100 question personality test',
  '100 question ADHD test',
  'printable personality report PDF',
  'Mindora Dossier PDF',
  'free psychometric test online',
  'educational psychological assessment',
  'non diagnostic ADHD screen',
  'OCEAN personality test free',
  'workplace personality assessment',
  'career fit assessment free',
  'professional development quiz',
  'self insight assessment',
  'trait profile PDF report',
  'free online psychology test',
  'instant personality results',
  'free mental health screening educational',
  'focus and attention test free',
  'executive function quiz',
  'relationship attachment test',
  'love style quiz free',
  'enneagram type test free',
  'DISC personality profile free',
  'emotional intelligence quiz free',
  'Jungian archetype quiz',
  'political identity quiz free',
  'neurodiversity screening educational',
  'autism traits quiz free',
  'depression mood screen free',
  'strengths based assessment',
  'VIA character strengths free',
  'free assessment library',
  'MindoraInsight free tests',
  'take free personality quiz',
  'print Mindora dossier',
  'extended personality report',
  'reference backed assessment',
  'calm professional assessments',
  'work mentality test',
  'team personality assessment',
  'leadership style quiz free',
  'communication style DISC',
  'secure attachment quiz',
  'anxious attachment quiz',
  'avoidant attachment quiz',
  'words of affirmation love language',
  'quality time love language quiz',
  'ADHD inattentive traits quiz',
  'ADHD hyperactive traits quiz',
  'combined ADHD pattern screen',
  'sensory sensitivity autism quiz',
  'social communication traits quiz',
  'mood energy cycle quiz',
  'burnout vs bipolar educational',
  'narcissistic traits spectrum quiz',
  'trauma informed self screen',
  'borderline traits educational quiz',
  'free online ADHD screening adults',
  'best free personality test 2026',
  'accurate free Big Five test',
  'free career personality test',
  'printable PDF assessment report',
  'no signup personality test',
  'no PIN free assessments',
  'instant free psychometric results',
  'MindoraInsight library',
  '20 free assessments',
  '100 questions 15 minutes',
  'educational not diagnosis',
  'UK personality test free',
  'London assessment studio',
  'professional growth assessments',
  'self knowledge at work',
  'trait spectrum breakdown',
  'profile shape report',
  'free EQ workplace test',
  'free political values quiz',
].join(', ')

/** Extra high-intent phrases per NewMindora topic id. */
export const TOPIC_SEO_KEYWORDS: Record<string, string[]> = {
  personality: [
    'free OCEAN personality test',
    'five factor model quiz',
    'Big Five personality free',
    'personality trait spectrum',
    'free personality PDF report',
  ],
  big5: [
    'free Big Five test',
    'OCEAN test online free',
    'openness conscientiousness extraversion',
    'agreeableness neuroticism quiz',
    'scientific Big 5 assessment',
  ],
  sixteen: [
    'free 16 personalities test',
    'MBTI style quiz free',
    'personality type indicator free',
    'introvert extrovert quiz',
    'thinking feeling personality test',
  ],
  enneagram: [
    'free Enneagram test',
    'enneagram type quiz',
    'nine types personality test',
    'enneagram wings free',
    'core motivation quiz',
  ],
  autism: [
    'free autism spectrum test',
    'autism traits quiz adults',
    'AQ style educational screen',
    'sensory pattern quiz',
    'non diagnostic autism screen',
  ],
  adhd: [
    'free adult ADHD test',
    'free ADHD screening online',
    'ADHD pattern screen adults',
    'inattention hyperactivity quiz',
    'executive function ADHD quiz',
    'ASRS style educational screen',
  ],
  depression: [
    'free depression screening test',
    'mood screen quiz free',
    'PHQ style educational screen',
    'depression symptoms quiz',
    'low mood energy assessment',
  ],
  love: [
    'free love languages test',
    'love style quiz',
    'five love languages free',
    'words of affirmation quiz',
    'how I give and receive love',
  ],
  attachment: [
    'free attachment style quiz',
    'secure anxious avoidant quiz',
    'adult attachment assessment',
    'relationship attachment test free',
    'bonding style quiz',
  ],
  strengths: [
    'free strengths finder test',
    'talent domain quiz',
    'CliftonStrengths style free',
    'natural strengths assessment',
    'signature strengths quiz',
  ],
  career: [
    'free career aptitude test',
    'career fit quiz free',
    'job personality match',
    'work environment assessment',
    'career path personality test',
  ],
  archetype: [
    'free archetype test',
    'Jungian archetype quiz',
    'hero caregiver rebel quiz',
    'character archetype assessment',
    'story archetype personality',
  ],
  political: [
    'free political compass test',
    'political identity quiz',
    'economic social values quiz',
    'left right spectrum quiz',
    'political values assessment free',
  ],
  disc: [
    'free DISC assessment',
    'DISC personality test free',
    'dominance influence steadiness',
    'workplace DISC profile',
    'communication style DISC quiz',
  ],
  eq: [
    'free emotional intelligence test',
    'free EQ test online',
    'EQ workplace assessment',
    'emotion regulation quiz',
    'empathy self awareness test',
  ],
  character: [
    'free character strengths test',
    'VIA strengths quiz free',
    'virtue signature strengths',
    'character strengths assessment',
    'positive psychology strengths test',
  ],
  bpd: [
    'BPD traits quiz educational',
    'emotion intensity quiz free',
    'borderline traits screen non diagnostic',
    'relationship intensity assessment',
    'emotional regulation traits quiz',
  ],
  bipolar: [
    'bipolar spectrum quiz educational',
    'mood cycle energy quiz',
    'hypomania pattern screen',
    'mood energy assessment free',
    'non diagnostic bipolar screen',
  ],
  narcissism: [
    'free narcissism test',
    'narcissistic traits quiz',
    'self focus recognition quiz',
    'narcissism spectrum assessment',
    'grandiose traits educational quiz',
  ],
  trauma: [
    'trauma patterns quiz free',
    'trauma informed self screen',
    'PTSD style educational quiz',
    'stress aftereffects assessment',
    'trauma response patterns quiz',
  ],
}

export function topicSeoKeywords(slug: string, title: string): string {
  const extras = TOPIC_SEO_KEYWORDS[slug] ?? []
  const base = [
    `free ${title} test`,
    `free ${title} quiz`,
    `${title} assessment online`,
    `${title} 100 questions`,
    `${title} PDF report`,
    'MindoraInsight',
    'Mindora Dossier PDF',
    'free psychometric test',
    'instant results printable PDF',
    'educational not a diagnosis',
  ]
  return [...base, ...extras].join(', ')
}
